// NOS VAMOS A CREAR UN METODO PARA DESPUES PROBARLO 

// NOS VAMOS A CREAS UNA FUNCION SUMA

const suma = (num1,num2)=>{
    return num1 + num2 
}

 export default suma // SE PUEDE PONER EL EXPORT ANTES DEL CONST CUALQUIER FORMA ESTA BIEN 